export const FETCH_PRODUCTS_TYPE = 'FETCH_PRODUCTS_TYPE';

export const FETCH_PRODUCTS_SELL_FAST = 'FETCH_PRODUCTS_SELL_FAST';

export const FETCH_NEW_PRODUCTS = 'FETCH_NEW_PRODUCTS';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const FETCH_DETAIL_PRODUCT = 'FETCH_DETAIL_PRODUCT';

export const FETCH_USER = 'FETCH_USER';

export const FETCH_PRODUCT_CART = 'FETCH_PRODUCT_CART';